version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Zurich
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: web3
    versions:
    - 1.3.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: eslint-import-resolver-typescript
    versions:
    - 2.3.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
